; PlatformIO Project Configuration File
; Auto-Timer-System — ESP32 38-pin, DS1307, OLED SSD1309 SPI, 4 relay
; Web UI nap qua LittleFS (thu muc /data)

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

; Toc do Serial monitor
monitor_speed = 115200

; Dung LittleFS cho file he thong (thay vi SPIFFS mac dinh)
board_build.filesystem = littlefs
lib_ldf_mode = deep+
lib_deps =
	SPI
	Wire
	adafruit/RTClib@^2.1.4
	olikraus/U8g2@^2.36.18
	bblanchon/ArduinoJson@^7.2.2
	ricmoo/QRCode@^0.0.1
